import 'package:flutter/material.dart';

const YELLOW = 0xFFFFCD32;
const COLOR_YELLOW = Color(YELLOW);

const BLACK = 0xFF222222;
const COLOR_BLACK = Color(BLACK);

const WHITE = 0xFFFFFFFF;
const COLOR_WHITE = Color(WHITE);

//透明度0.3的黑
const TRANSLUCENT_WHITE_ZERO_POINT_THREE = 0x4CFFFFFF;
const COLOR_TRANSLUCENT_WHITE_ZERO_POINT_THREE =
    Color(TRANSLUCENT_WHITE_ZERO_POINT_THREE);

//透明度0.5的白
const TRANSLUCENT_WHITE_ZERO_POINT_FIVE = 0x7FFFFFFF;
const COLOR_TRANSLUCENT_WHITE_ZERO_POINT_FIVE =
    Color(TRANSLUCENT_WHITE_ZERO_POINT_FIVE);

//透明度0.8的白
const TRANSLUCENT_WHITE_ZERO_POINT_EIGHT = 0xCCFFFFFF;
const COLOR_TRANSLUCENT_WHITE_ZERO_POINT_EIGHT =
    Color(TRANSLUCENT_WHITE_ZERO_POINT_EIGHT);

//透明度0.5的黑
const TRANSLUCENT_BLACK_ZERO_POINT_EIGHT = 0x7FFFFFFF;
const COLOR_TRANSLUCENT_BLACK_ZERO_POINT_EIGHT =
Color(TRANSLUCENT_BLACK_ZERO_POINT_EIGHT);