const YELLOW = 0xFFFFCD32;
const BLACK = 0xFF222222;
const WHITE = 0xFFFFFFFF;
//透明度0.5的白
const TRANSLUCENT_WHITE_ZERO_POINT_FIVE = 0x7FFFFFFF;
//透明度0.3的黑
const TRANSLUCENT_WHITE_ZERO_POINT_THREE = 0x44FFFFFF;
const indicatorActiveWhite = 0xFFFAFBE5;

